#!/system/bin/sh
#

insmod /system/lib/modules/xpad.ko
insmod /system/lib/modules/hid-gaff.ko
insmod /system/lib/modules/hid-pl.ko
insmod /system/lib/modules/hid-sony.ko
insmod /system/lib/modules/ft5x_ts.ko
insmod /system/lib/modules/8192cu.ko

echo "done Additional Modules Autoload"
